name: public_test 
description: |
   service for public \n
       rabbitmq ip: 10.42.1.200 \n
       redis    ip: 10.42.1.201 \n
       master   ip: 10.42.1.202 \n
       slave    ip: 10.42.1.203 \n
version:  1.0.0
category:  public_service
maintainer:  weds
license: public:v1.0.0
projectURL: https://github.com/muzongchuan006/demo
