name: public_test 
description: |
   service for public 
description: |
   |    rabbitmq ip: 10.42.1.200 
   |    redis    ip: 10.42.1.201 
description: |
   |    master   ip: 10.42.1.202 
description: |
   |    slave    ip: 10.42.1.203 
version:  1.0.0
category:  public_service
maintainer:  weds
license: public:v1.0.0
projectURL: https://github.com/muzongchuan006/demo
