version: '2'
services:
  postgresql-master:
     image: 10.0.0.96:5000/database/pg_ip_pglogical_pathman:v2
     hostname: postgresqlmaster
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=102
     networks: 
       - docker_gwbridge
     ports:
       - "5390:5432"
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup
       - /opt/test/pgsqlmaster/9.6/data:/var/lib/pgsql/9.6/data
     privileged: true
     tty: true
  postgresql-slave:
     image: 10.0.0.96:5000/database/pg_ip_pglogical_pathman:v2
     hostname: postgresqlslave
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - "5380:5432"
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup
       - /opt/test/pgsqlslave/9.6/data:/var/lib/pgsql/9.6/data
     privileged: true
     tty: true
