version: '2'
.catalog:
  name: "public_test"
  version: "v0.0.1"
  description: "public service for test."
  uuid: public-0
  minimum_rancher_version: v1.0.0
services:
  rabbitmq:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 1
      response_timeout: 2000
      port: 15672
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
    labels:
      io.rancher.container.requested_ip: "10.42.1.200"
  redis:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 1
      response_timeout: 2000
      port: 6379
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
    labels:
      io.rancher.container.requested_ip: "10.42.1.201"
  postgresql-master:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
    labels:
      io.rancher.container.requested_ip: "10.42.1.202"
  postgresql-slave:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
    labels:
      io.rancher.container.requested_ip: "10.42.1.203"
