version: '2'
.catalog:
  name: "demo_test"
  version: "v0.0.1"
  description: "A demo for test."
  uuid: demo-0
  minimum_rancher_version: v1.0.0
services:
  rabbitmq:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 1
      response_timeout: 2000
      port: 15672
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  redis:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 1
      response_timeout: 2000
      port: 6379
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  postgresqlmaster:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  postgresqlslave:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
